[package]
name = "torrent-cleaner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reqwest = { version = "0.12.24", features = ["cookies", "json"] }
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
chrono = "0.4.42"
